#!/usr/bin/python3
# coding: utf-8

'''KVM/libvirt to Ganeti migration script'''
# Copyright (C) 2020 Antoine Beaupré <anarcat@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import division, absolute_import
from __future__ import print_function, unicode_literals

from invoke import Collection


from fabric_tpa import ganeti
from fabric_tpa import VerboseProgram


def main():
    program = VerboseProgram(namespace=Collection.from_module(ganeti))
    program.run()


if __name__ == '__main__':
    main()
