#!/bin/sh

DELAY=${DELAY:-5}
HOST="$1"

if [ -z "$HOST" ]; then
    echo "Usage: $0 <host>"
    exit 1
fi

echo "DEPRECATED: use 'reboot --node $HOST' instead"

printf "about to reboot host %s, continue? " "$HOST"

read -r _

ssh "root@$HOST" /sbin/shutdown -r "+${DELAY}" new kernel &&
echo "waiting ${DELAY} minutes for reboot to happen..." &&
sleep "${DELAY}m" &&
echo "waiting for host to go down for 30 seconds..." &&
sleep 30 &&
echo "waiting up to 2 minutes for $HOST to come back..." &&
date &&
ping -c 10 -w 120 "$HOST"

ssh "$HOST" uptime && echo "check uptime above"
