#!/bin/sh

HOST="$1"

if [ -z "$HOST" ]; then
    echo "Usage: $0 <host>"
    exit 1
fi

echo "DEPRECATED: remove this script after we converted from libvirt"

# no prompt because tor-libvirt-reboot prompts

echo "showing motd to see affected guests" &&
ssh "$HOST" cat /etc/motd &&
ssh -tt "root@$HOST" tor-libvirt-reboot ; \
echo "waiting 30 seconds for host to go down..." &&
sleep 30 &&
echo "waiting up to 2 minutes for $HOST to come back" &&
ping -c 10 -w 120 "$HOST" ; \
ssh -tt "root@$HOST" tor-libvirt-luks-start
