#!/bin/bash

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
	echo >&2 "Usage: $0 <minwait>:<host> [<ignored>]"
	exit 1
fi

minwaithost="$1"
host="${minwaithost##*:}"
minwait="${minwaithost%%:*}"

if [ "$minwaithost" != "$minwait:$host" ] ; then
	echo >&2 "Cannot split argument $minwaithost properly."
	exit 1
fi


echo $host after $minwait mins
ssh -l root $host -t "
	if /usr/lib/nagios/plugins/dsa-check-running-kernel && ! (/usr/lib/nagios/plugins/dsa-check-libs | egrep --color 'systemd|dbus-daemon'); then
		echo 'Everything ok.'
		sleep 5
		exit
	fi

	echo 'Starting a screen'
	screen -S reboot-job -d -m  sh -c 'sleep ${minwait}m ; /sbin/shutdown -r 10 \"Kernel (mass) reboot issued by `whoami`.\" < /dev/null '
	echo 'done.'
	sleep 5
"
