#!/bin/bash

set -e
set -u

if [ "$#" = 0 ]; then
  echo >&2 "Usage: $0 <host> [<host> ..]"
  echo >&2 "e.g.:"
  echo >&2 " $0 \$(ldapsearch -h db.debian.org -x -ZZ -b dc=debian,dc=org -LLL '(&(hostname=*.debian.org)(rebootPolicy=justdoit))' hostname | awk '\$1 == \"hostname:\" {print \$2}' | sort -R)"
  exit 1
fi

if ! [ -x /usr/bin/ldapsearch ]; then
  echo "No ldap-utils installed. On Debian machine you need to run:"
  echo "  sudo apt install ldap-utils"
  exit 1
fi

WAITHOSTS=""
WAITINTERVAL=${WAITINTERVAL:-2}
min=0
while [ "$#" -gt 0 ]; do
  WAITHOSTS="$WAITHOSTS $min:$1"
  min=$(( min + WAITINTERVAL ))
  shift
done

echo Hosts: $WAITHOSTS
echo "Continue (or ^C)?"
read x

b=$(basename $(readlink -f $0))
d=$(dirname $(readlink -f $0))
"$d/Genric-run-multi" "$b" "$d/One-torproject-reboot-generic" $WAITHOSTS
