#!/bin/sh

set -e
set -u

# TODO: this entire hook should be managed by grml-debootstrap
# itself. it's mostly necessary because grml doesn't support multiple
# disks, see: https://github.com/grml/grml-debootstrap/issues/152

# TODO: hardcoded secondary disk, should be guessed?
DISK2="/dev/nvme1n1"

echo "I: bind mounting everything"
for fs in dev proc run sys  ; do
    mount -o bind /$fs "$MNTPOINT/$fs"
done

# TODO: doesn't this belong in grml-debootstrap itself?
echo "I: regenerating mdadm.conf..."
chroot "$MNTPOINT" sh -c "/usr/share/mdadm/mkconf > /etc/mdadm/mdadm.conf"

# assume we need to rebuild initrd...
echo "I: rebuilding initramfs..."
chroot "$MNTPOINT" update-initramfs -u

echo "I: rebuilding grub config..."
chroot "$MNTPOINT" update-grub

if [ -e "$DISK2" ]; then
    echo "I: installing grub on secondary disk $DISK2"
    if chroot "$MNTPOINT" grub-install "$DISK2"; then
        grub_success() {
            true
        }
    else
        grub_success() {
            false
        }
    fi
else
    grub_success() {
        false
    }
fi
if grub_success; then
    if ls /dev/md* ; then
        echo "W: $DISK2 not found, grub NOT INSTALLED on secondary disk of md array"
    else
        echo "I: $DISK2 not found, assuming hardware RAID"
    fi
fi

echo "I: current crypttab:"
cat "$MNTPOINT/etc/crypttab" || true

echo "I: unmounting"
for fs in dev proc run sys ; do
    umount "$MNTPOINT/$fs" || true
done
grub_success
