#!/bin/sh

set -e
set -u

# TODO: merge with tor-puppet/3rdparty/modules/ganeti/files/instance-debootstrap/hooks/random-root-password
# main differences:
# * MNTPOINT instead of TARGET (grml vs ganeti interface)
# * custom urandom generator instead of (possibly unavailable) pwqgen
# * do not require password change on first login
printf "setting root password to: "
( printf "root:" ; tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 30 | tee -a /dev/stderr ) | chpasswd -c SHA512 -R "$MNTPOINT"
