#!/bin/sh

# populate authorized_keys in target $MNTPOINT so that we can login later.
#
# should be part of grml-debootstrap, see https://github.com/grml/grml-debootstrap/issues/151
set -e
set -u

AUTHORIZED_KEYS_SOURCE=${AUTHORIZED_KEYS_SOURCE:-$HOME/.ssh/authorized_keys}
AUTHORIZED_KEYS_TARGET=${AUTHORIZED_KEYS_TARGET:-$MNTPOINT/root/.ssh/}
echo "I: copying $AUTHORIZED_KEYS_SOURCE to "$AUTHORIZED_KEYS_TARGET""
mkdir -p "$AUTHORIZED_KEYS_TARGET"
chmod 0700 "$AUTHORIZED_KEYS_TARGET"
cp $AUTHORIZED_KEYS_SOURCE "$AUTHORIZED_KEYS_TARGET"
