#!/bin/sh

# mountpoint from grml or first argument or current directory
MNTPOINT=${MNTPOINT:-${1:-.}}
AUTHKEYS_SOURCE=${AUTHKEYS_SOURCE:-$HOME/.ssh/authorized_keys}

echo "I: setting up LUKS boot on $MNTPOINT..."

PVNAME=$(lvs --noheadings -o vg_name $(findmnt -o SOURCE -l -n $MNTPOINT) | sed 's/^ *//')
UUID=$(blkid -s UUID -o value $(cryptsetup status $PVNAME | sed -n '/device:/{s/.*: *//;p}'))

echo "I: UUID: $UUID, PVNAME: $PVNAME"

if ! [ -f $AUTHKEYS_SOURCE ] || ! [ -s $AUTHKEYS_SOURCE ]; then
    echo "$AUTHKEYS_SOURCE missing or empty" >&2
    AUTHKEYS_SOURCE=$(mktemp)
    printf "enter valid SSH authorized keys string followed by control-d: "
    cat > $AUTHKEYS_SOURCE
fi

echo "I: installing packages..."

DEBIAN_FRONTEND=noninteractive chroot "$MNTPOINT" apt-get install -y dropbear-initramfs cryptsetup console-setup

echo "I: adding SSH keys from $AUTHKEYS_SOURCE"
sed -e '/^ssh-/ s#^#no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="/bin/cryptroot-unlock" #' "$AUTHKEYS_SOURCE" > "$MNTPOINT/etc/dropbear-initramfs/authorized_keys"


echo "I: setting up network hook in initramfs"

mkdir -p $MNTPOINT/etc/default/grub.d
echo 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX net.ifnames=0"' > $MNTPOINT/etc/default/grub.d/local-ifnames.cfg

# unsure why this is necessary, or how this works
cat > "$MNTPOINT/etc/initramfs-tools/scripts/init-premount/local-hetzner-default-gw" << 'EOF'
#!/bin/sh

PREREQ=""
prereqs() {
  echo "$PREREQ"
}

case $1 in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

configure_networking

log_begin_msg "Checking if we find the initramfs config and network info."
if [ -e /conf/initramfs.conf ]; then
  . /conf/initramfs.conf
fi
if [ -z "$DEVICE" ]; then
  log_begin_msg "No networking device set."
  exit
fi

if [ -e /run/net-$DEVICE.conf ]; then
  log_begin_msg "No /run/net-$DEVICE.conf found."
  . /run/net-$DEVICE.conf
fi

if [ -z "$IPV4GATEWAY" ]; then
  log_begin_msg "No ipv4 gateway info found."
  exit
fi

log_begin_msg "Adding a host route to the ipv4 gateway $IPV4GATEWAY on $DEVICE"
ip route add "$IPV4GATEWAY"/32 dev "$DEVICE"
log_begin_msg "Setting default route"
ip route add default via "$IPV4GATEWAY" dev "$DEVICE"
EOF
chmod +x "$MNTPOINT/etc/initramfs-tools/scripts/init-premount/local-hetzner-default-gw"

echo "I: setting DEVICE=eth0 in initramfs.conf"
sed -i -e 's/^DEVICE=$/DEVICE=eth0/' "$MNTPOINT/etc/initramfs-tools/initramfs.conf"

echo "I: configuring crypttab"
cat > "$MNTPOINT/etc/crypttab" << EOF
$PVNAME UUID=$UUID none luks
EOF

echo "I: bind mounting everything"
for fs in dev proc run sys  ; do
    mount -o bind /$fs "$MNTPOINT/$fs"
done
echo "I: regenerating initramfs"
chroot $MNTPOINT update-initramfs -u -k all
echo "I: updating grub"
chroot $MNTPOINT update-grub
for device in /dev/sd[a-z]; do
    echo "I: installing grub on $device"
    chroot $MNTPOINT grub-install $device
done
echo "I: unmounting"
for fs in dev proc run sys ; do
    umount "$MNTPOINT/$fs"
done
