#!/bin/sh

# Generate an LDAP snippet for this host.
#
# Copyright 2019 Antoine Beaupré <anarcat@torproject.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You probably already have access to a copy of the GNU General Public
#   License or you can find one on the Internet; if not, write to the
#   copyright holder or to the Free Software Foundation, Inc., 59 Temple
#   Place, Suite 330, Boston, MA 02111-1307 USA.

LOCATION=${LOCATION:-"Falkenstein, Saxony, Germany"}
# keep empty on physical hosts
PARENT=${PARENT:-""}
DESCRIPTION=${DESCRIPTION:-"XXX"}
PURPOSE=${PURPOSE:-"XXX"}
IPADDR=${IPADDR:-$(ip -o -4 route get 255.255.255.255 | sed 's/.* src //;s/ .*//')}
IP6ADDR=${IP6ADDR:-$(ip -o -6 route get ffff:: | sed 's/.* src //;s/ .*//')}
HOSTNAME=${HOSTNAME:-$(hostname)}
FQDN=${FQDN:-$(hostname -f)}

cat <<EOF
add host=$HOSTNAME,ou=hosts,dc=torproject,dc=org
host: $HOSTNAME
hostname: $FQDN
objectClass: top
objectClass: debianServer
l: $LOCATION
distribution: Debian
access: restricted
admin: torproject-admin@torproject.org
architecture: amd64
physicalHost: $PARENT
description: $DESCRIPTION
purpose: $PURPOSE
ipHostNumber: $IPADDR
ipHostNumber: $IP6ADDR
EOF

for key in /etc/ssh/ssh_host_*_key.pub ; do
    printf "sshRSAHostKey: "
    cat $key
done | grep -v 'ecdsa-sha2-nistp256'
for key in /etc/dropbear-initramfs/dropbear_*_host_key ; do
    printf "sshRSAHostKey: "
    dropbearkey -y -f $key | grep -e ^ssh- -e ^ecdsa-
done | grep -v 'ssh-dss ' | sed -e 's/$/ (initramfs)/'
