#!/bin/sh

set -e

# note: hetzner systems apparently don't do EFI as of 2019-07

apt install fai-setup-storage

CURDIR=$(dirname "$0")

setup-storage -f "$CURDIR/disk_config/gnt-fsn" -X

. /tmp/fai/disk_var.sh

mkdir /target
mount "$ROOT_PARTITION" /target
mkdir /target/boot
mount "$BOOT_PARTITION" /target/boot
